apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: bW9uZ291c2Vy #can be coded in the terminal using command echo -n username | base64, replace value of username
  password: bW9uZ29wYXNzd29yZA==
